name: "Unit Tests"

on: workflow_call

env:
  CGO_ENABLED: 0

jobs:
  test-linux:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
        - "5005:5000"
        env:
          REGISTRY_AUTH: htpasswd
          REGISTRY_AUTH_HTPASSWD_REALM: Registry
          REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
          REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
          - /tmp:/data
          - ./hack/registry/auth:/auth

    name: Go unit tests (ubuntu-latest)
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: ./go.mod

    - name: Set up gotestfmt
      uses: gotesttools/gotestfmt-action@8b4478c7019be847373babde9300210e7de34bfb # v2.2.0

    - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # 4.0.0
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg
        key: golangci-lint.cache-{platform-arch}-{interval_number}-{go.mod_hash}
        restore-keys: |
          golangci-lint.cache-{interval_number}-
          golangci-lint.cache-

    - run: make citest
      env:
        CGO_ENABLED: 1 # go test -race requires cgo

    - run: go build -ldflags="-s -w -X main.version=$(git describe --tags) -X main.date=$(date +"%Y-%m-%dT%H:%M:%S%z")"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # 4.0.1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}