name: 'Push'

on:
  push:
    branches: main
    tags: v*

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-lint:
    uses: ./.github/workflows/_golangci-lint.yml
  call-test:
    uses: ./.github/workflows/_unit.yml
  call-gorelease:
    needs: [call-lint, call-test]
    uses: ./.github/workflows/_gorelease.yml